// ============================================================================
// 719_Combined.ino — single-file build of 719_GlideMission.
// AUTO-GENERATED by concatenating the split sketch in Arduino build order:
//   719_GlideMission.ino + esekf.ino + gps.ino + imu.ino + logger.ino + mission.ino
// Do not edit here — edit the split files and regenerate.
// ============================================================================


// ############################################################################
// #### Begin: 719_GlideMission.ino
// ############################################################################

#include <Arduino.h>
#include <Arduino_LSM6DSOX.h>
#include <Servo.h>
#include <SPI.h>
#include <SD.h>
#include <math.h>
#include <rtos.h>

// Set 1 to enable M4 (GPS approach region) and M5 (helicopter descent).
// Fill APPROACH_TARGET_N/E_M from mission plan before enabling.
#define ENABLE_APPROACH_PHASES 0

// ========================= Edit each flight =========================
// These are the only values you should need to change between flights.

// Servo positions measured with sweep_aero_logger (deg = (us-500)*180/2000).
// Flat (glide) configuration:
static const float WING_FLAT_LEFT_DEG  = 96.75f;  // 1575 us
static const float WING_FLAT_RIGHT_DEG = 90.00f;  // 1500 us
// Fold configuration: wings biased ±30° from flat to prevent collision
// during morph sweep. Verify clearance on the bench before first flight.
static const float WING_FOLD_LEFT_DEG  = 66.75f;  // flat - 30°
static const float WING_FOLD_RIGHT_DEG = 120.00f; // flat + 30°
// Morph: 0° = folded (500 us), 180° = fully deployed (2500 us).
static const float MORPH_FOLD_DEG    = 0.0f;
static const float MORPH_OPEN_DEG    = 180.0f;
// Tail neutral.
static const float TAIL_HOLD_DEG     = 90.0f;     // 1500 us
// Helicopter/autorotation configuration (M5): wings rotated ~90° in
// opposite directions relative to flat. VERIFY directions on bench.
static const float HELI_LEFT_DEG  = 6.75f;    // flat - 90° → 575 us
static const float HELI_RIGHT_DEG = 180.0f;   // flat + 90° → 2500 us

// M3 PID targets (level glide).
static const float ROLL_TARGET_DEG  = 0.0f;
static const float PITCH_TARGET_DEG = 0.0f;

// M3→M4: target landing point in local NEU metres from GPS origin.
// Leave at 0/0 while ENABLE_APPROACH_PHASES is 0.
static const float APPROACH_TARGET_N_M = 0.0f;
static const float APPROACH_TARGET_E_M = 0.0f;

// Log window: starts at t=0 (end of calibration), closes after RECORD_END_S.
// NOTE: ground wait + drone carry count against this window. 600 s proved
// risky (log could close before release on a slow launch cycle) — 1200 s
// costs ~10 MB of SD and removes the risk.
static const float RECORD_START_S = 0.0f;
static const float RECORD_END_S   = 1200.0f;  // 20-minute cap

// ========================= Mission parameters =========================

// --- M0 → M1: free-fall detection ---
//
// THRESHOLD: In free fall, gravity is cancelled; the accelerometer reads ≈0 m/s².
// 0.3 g (2.94 m/s²) sits above typical drone vibration (< 0.15 g) and below
// any real attitude where gravity contributes at least cos(angle)·g.
// Raise if the carrier drone vibrates more than expected.
static const float FREE_FALL_THRESHOLD_MPS2 = 0.30f * 9.80665f; // 2.94 m/s²

// CONFIRM_FRAMES: 10 frames @ 80 Hz = 125 ms. Long enough to reject a single
// motor pulse; short enough to lose < 8 cm of altitude before detection.
static const uint8_t FREE_FALL_CONFIRM_FRAMES = 10;

// --- M1 → M2 (wing deployment): speed + altitude gates ---
//
// V_OPEN_MIN: minimum ESEKF speed before wings deploy.
// Too low → stall on opening (Reynolds number insufficient for large light wing).
// Raise from first drop tests if the glider stalls.
static const float V_OPEN_MIN_MPS = 8.0f;

// H_OPEN_MIN: minimum AGL altitude at the moment wings open.
// Budget: H_OPEN_MIN > H_FORCE_OPEN_M + VZ_max · T2_OPEN_S ≈ 25 + 15·0.8 = 37 m.
static const float H_OPEN_MIN_M = 40.0f;

// H_FORCE_OPEN: emergency floor — open regardless of speed if never triggered.
// Minimum: 0.5·g·T2_OPEN_S² ≈ 3 m; 25 m gives large safety margin.
static const float H_FORCE_OPEN_M = 25.0f;

// --- M2: wing deployment transient ---
// Wings open in under 1 second; morph is ramped linearly over T2_OPEN_S.
static const float T2_OPEN_S = 0.8f;

// --- M3/M4: GPS navigation (bank-to-turn guidance) ---
//
// Steers toward APPROACH_TARGET_N/E_M by commanding a roll target from the
// heading error (desired bearing - current ground track). Default target is
// 0/0 = the GPS origin, i.e. the power-on location — the glider flies back
// over its launch point unless other coordinates are set.
// Set 0 to disable and hold wings level (straight glide) as before.
#define ENABLE_GPS_NAVIGATION 1
// Roll command per degree of heading error. 0.4 → 40° error saturates the
// bank limit. If the aircraft turns AWAY from the target in flight, the
// servo direction convention is inverted — negate this gain.
static const float NAV_KP_ROLL_PER_HDG_DEG  = 0.4f;
// Bank limit for navigation turns. Conservative for a light glider; raising
// it tightens the turn radius but increases sink rate and stall risk.
static const float NAV_MAX_BANK_DEG         = 15.0f;
// Below this ground speed the track angle from velocity is unreliable
// (atan2 of noise) — hold wings level instead of steering.
static const float NAV_MIN_GROUND_SPEED_MPS = 3.0f;
// Inside this radius stop steering (bearing changes too fast when close);
// hold wings level and let M4 approach logic take over.
static const float NAV_ARRIVAL_RADIUS_M     = 20.0f;

// --- Wind guard (anti-circling in strong headwind) ---
//
// Failure mode without this guard: wind stronger than airspeed blows the
// aircraft backward. Ground track then points AWAY from the target, the
// nav loop sees ~180° heading error and commands a maximum-bank turn.
// But in overwhelming wind no heading makes progress, so the turn never
// closes — the aircraft circles endlessly, sinking faster (banked flight)
// while drifting downwind. Strictly worse than doing nothing.
//
// Guard: if a saturated bank command persists for NAV_STUCK_TURN_MS while
// closing speed on the target stays negative, declare the turn futile and
// hold wings level (minimum sink). Resume navigation automatically if the
// closing speed turns positive (wind eased, or drift rotated us favourably).
static const uint32_t NAV_STUCK_TURN_MS       = 5000;
// Closing speed must exceed this (m/s) to leave the wings-level hold.
// Nonzero so GPS velocity noise cannot flap the state.
static const float    NAV_RESUME_CLOSE_MPS    = 0.5f;

// --- Headwind penetration mode (engaged by the wind guard) ---
//
// When the stuck-turn detector concludes the wind beats our normal glide
// airspeed, pull the morph partially back instead of giving up. Partial
// sweep does two things at once: less wing area raises the trim airspeed,
// and the aft-shifted neutral point pitches the nose down naturally —
// both push airspeed above the wind so ground progress (and steering
// authority over the ground track) come back.
#define ENABLE_PENETRATION_MODE 1
// Servo-space target for the partial sweep, 40° back from fully open.
// PLACEHOLDER GEOMETRY: the servo→wing-sweep mapping depends on the morph
// linkage. Bench-verify that this value gives the intended "tens of
// degrees" of sweep AND that the wing stays stable at that setting.
static const float    PENETRATION_MORPH_DEG     = 140.0f;
// Do not engage below this AGL: penetration raises sink rate, and low down
// the remaining altitude is better spent in minimum-sink level hold.
static const float    PENETRATION_MIN_AGL_M     = 25.0f;
// If after this long in penetration the closing speed is still negative,
// even the raised airspeed cannot beat the wind — fall back to level hold.
static const uint32_t PENETRATION_GIVEUP_MS     = 8000;
// Leave penetration once closing speed is healthy. Deliberately higher than
// NAV_RESUME_CLOSE_MPS: reopening the wings drops airspeed, so exit only
// with margin, or the two states would flap.
static const float    PENETRATION_EXIT_CLOSE_MPS = 2.0f;

// --- M3 → M4: approach zone (only active if ENABLE_APPROACH_PHASES) ---
static const float   APPROACH_RADIUS_M        = 15.0f;
static const uint8_t APPROACH_CONFIRM_CYCLES  = 10;
// Altitude floor for M4: force the approach/heli transition at this AGL
// even if the target zone was never reached — mirrors H_FORCE_OPEN_M in M1.
// Rationale: below ~15 m there is not enough altitude to keep gliding
// toward the target anyway; landing in heli configuration (low vertical
// speed, no horizontal speed) is always safer than gliding into the ground.
// Requires descending (v[2] < 0), same guard as the M1 triggers.
static const float   H_FORCE_APPROACH_M       = 15.0f;

// --- M5: helicopter descent ---
// Morph servo modulates descent rate based on measured vertical speed.
// Positive wind → increase morph angle (more blade area → slower descent).
static const float HELI_MORPH_BASE_DEG     = 90.0f;
static const float HELI_MORPH_MIN_DEG      = 70.0f;
static const float HELI_MORPH_MAX_DEG      = 130.0f;
static const float HELI_NORMAL_DESCENT_MPS = 2.5f;
static const float HELI_FAST_DESCENT_MPS   = 3.5f;
static const float HELI_GAIN_DEG_PER_MPS   = 8.0f;
static const float HELI_VD_FILTER_ALPHA    = 0.10f;

// ========================= Timing and IO =========================

static const uint32_t SERIAL_BAUD            = 115200;
static const uint32_t SERIAL_WAIT_MS         = 1500;
static const uint32_t GPS_BAUD               = 115200;
static const uint16_t GPS_MEASUREMENT_PERIOD_MS = 100; // 10 Hz

static const float    LOOP_HZ    = 80.0f;
static const float    DT_NOMINAL = 1.0f / LOOP_HZ;
static const uint32_t LOOP_DT_US = (uint32_t)(1000000.0f / LOOP_HZ);

static const float    SD_LOG_HZ     = 20.0f;
static const uint32_t SD_LOG_DT_US  = (uint32_t)(1000000.0f / SD_LOG_HZ);
static const int      SD_CS_PIN     = 10;
static const uint8_t  SD_FLUSH_EVERY_N = 10;

static const int   SERVO_LEFT_PIN  = 4;
static const int   SERVO_RIGHT_PIN = 3;
static const int   SERVO_MORPH_PIN = 5;
static const int   SERVO_TAIL_PIN  = 6;
static const int   SERVO_MIN_US    = 500;
static const int   SERVO_MAX_US    = 2500;
static const float SERVO_MIN_DEG   = 0.0f;
static const float SERVO_MAX_DEG   = 180.0f;
// Servo command slew limit. Two purposes:
// (1) mode transitions become controlled ramps instead of step loads on the
//     light airframe; (2) staggers stall-current draw through the TPS61088
//     5 V boost rail — several servos stepping at once caused brownouts on
//     earlier builds (see 708 SD-init notes).
// Must stay above the M2 morph sweep rate (180° / 0.8 s = 225°/s).
static const float SERVO_SLEW_LIMIT_DPS = 300.0f;

static const float G_MPS2       = 9.80665f;
static const float DEG_TO_RAD_F = 0.017453292519943295f;
static const float RAD_TO_DEG_F = 57.29577951308232f;

// ========================= ESEKF configuration =========================
//
// Error-state vector: dx = [dθ(3) dv(3) dp(3) dbg(3) dba(3)]
//   0..2   attitude error (rad)
//   3..5   world NEU velocity error (m/s)
//   6..8   world NEU position error (m)
//   9..11  gyro bias error (rad/s)
//   12..14 accelerometer bias error (m/s²)
static const int ESEKF_N = 15;

static const float GYRO_NOISE_RADPS      = 0.015f;
static const float ACCEL_NOISE_MPS2      = 0.18f;
static const float GYRO_BIAS_RW_RADPS    = 0.0008f;
static const float ACCEL_BIAS_RW_MPS2    = 0.006f;
static const float ACCEL_LEVEL_NOISE_RAD = 3.0f * DEG_TO_RAD_F;

// Accelerometer magnitude gate for attitude correction.
// Outside [0.82g, 1.18g] the aircraft is accelerating and the reading
// no longer represents gravity alone. Free fall and deployment loads
// both fall outside this window automatically.
static const float ACCEL_GATE_LOW_MPS2  = 0.82f * G_MPS2;
static const float ACCEL_GATE_HIGH_MPS2 = 1.18f * G_MPS2;

// Angular rate gate for accel-based attitude leveling.
// Skip when body rotates faster than this — centripetal acceleration
// would corrupt the roll/pitch estimate. 0.25 rad/s ≈ 14°/s.
// Source: Kai Keller version, synthetic validation (roll RMSE 14.9→3.0 deg).
static const float ESEKF_LEVEL_RATE_GATE_RADPS = 0.25f;

static const float    GPS_POSITION_NOISE_FLOOR_M = 1.5f;
static const float    GPS_VERTICAL_NOISE_FLOOR_M  = 2.5f;
// Floor under the M10's reported sAcc (speed accuracy estimate, mm/s).
// Raw sAcc can reach 0.05 m/s in open sky; 0.25 m/s prevents over-weighting.
// During poor visibility sAcc rises automatically, loosening fusion.
static const float    GPS_VELOCITY_NOISE_MPS      = 0.25f;
static const uint32_t GPS_FIX_STALE_MS           = 1500;
static const uint8_t  GPS_ORIGIN_MIN_SATS         = 6;
static const float    GPS_ORIGIN_MAX_HACC_M        = 3.0f;
static const uint8_t  GPS_ORIGIN_STABLE_FIXES      = 3;

static const uint16_t CAL_SAMPLES = 500;
static const uint16_t CAL_DT_MS   = 4;

// ========================= Cascade PID configuration (M3) =========================
//
// Outer loop: angle error (deg) → desired angular rate (deg/s).
// Inner loop: rate error (deg/s) → servo deflection (deg).
// Tuning order: Kp_outer first (roll stiffness), then Kd_inner (rate damping).
static const float KP_OUTER_ROLL  = 1.2f;    // deg/s per deg error
static const float KP_OUTER_PITCH = 1.0f;
// Clamp on the outer-loop rate command. Without this a large angle error
// (e.g. upset) would request an unbounded rate; 60°/s keeps recovery brisk
// but well inside what the inner loop and servos can actually track.
static const float RATE_TARGET_LIMIT_DPS = 60.0f;
static const float KP_INNER_ROLL  = 0.08f;   // servo deg per deg/s error
static const float KP_INNER_PITCH = 0.08f;
static const float KI_INNER_ROLL  = 0.01f;   // integrator: correct steady trim
static const float KI_INNER_PITCH = 0.01f;
// Integrator state limit. The integral accumulates rate error (deg/s) over
// time, so its unit is degrees. Max trim authority = KI_INNER x limit
// = 0.01 x 400 = 4 deg — enough to correct steady trim offsets without
// giving the integrator enough authority to fight the pilot loops.
static const float INTEGRATOR_LIMIT_DEG   = 400.0f;
static const float ANGLE_DEADBAND_DEG     = 2.0f;   // ignore noise below this
static const float RATE_DEADBAND_DPS      = 1.5f;
// Wing servo neutral for PID mixing. Both servos centre at 90° in software;
// mechanical trim offsets (WING_FLAT_*) are used only for fold/deploy logic.
static const float PID_NEUTRAL_DEG        = 90.0f;
// Max deflection from PID_NEUTRAL_DEG each way: range is [60°, 120°].
// 30° gives ~50% more travel than the previous 20° while staying clear of
// mechanical limits (fold positions are ±30° from flat ≈ 67°/120°).
static const float CMD_LIMIT_DEG          = 30.0f;

// ========================= Data types =========================

struct ImuSample {
  float accel[3]; // m/s²
  float gyro[3];  // rad/s
  bool  valid;
};

struct GpsSample {
  bool     bytesSeen;
  bool     fix;
  bool     fresh;
  uint8_t  fixType;
  uint8_t  satellites;
  uint32_t iTowMs;
  uint32_t lastFusedTowMs;
  uint32_t receivedMs;
  double   latitudeDeg;
  double   longitudeDeg;
  float    altitudeM;
  float    hAccM;
  float    vAccM;
  float    sAccMps;      // speed accuracy from NAV-PVT byte 68, adaptive velocity noise
  float    velocityNed[3];
  uint8_t  month;        // 1–12, from NAV-PVT byte 6; 0 until first validDate packet
  uint8_t  day;          // 1–31, from NAV-PVT byte 7; 0 until first validDate packet
};

struct ESEKFState {
  float q[4];
  float v[3];
  float p[3];
  float bg[3];
  float ba[3];
  float P[ESEKF_N][ESEKF_N];
  bool  initialized;
};

// Mission phase identifiers.
enum FlightMode : uint8_t {
  MODE_CARRIED      = 0,  // M0: folded, being carried up by drone
  MODE_FREE_FALL    = 1,  // M1: released, building speed, still folded
  MODE_DEPLOYING    = 2,  // M2: morph sweeping open (< T2_OPEN_S)
  MODE_GLIDE        = 3,  // M3: wings open, cascade PID active
  MODE_APPROACH     = 4,  // M4: near target GPS zone, preparing for heli
  MODE_HELI_DESCENT = 5   // M5: helicopter/autorotation descent
};

enum RecordKind : uint8_t {
  RECORD_DATA = 0,
  RECORD_STOP = 1
};

// Wind-response state machine (see nav constants for the transitions).
enum NavWindState : uint8_t {
  NAV_WIND_NORMAL      = 0,  // normal bank-to-turn navigation
  NAV_WIND_PENETRATION = 1,  // partial sweep engaged, still steering
  NAV_WIND_LEVEL_HOLD  = 2   // turn futile even penetrated: min-sink hold
};

struct ControlRecord {
  uint8_t  kind;
  uint8_t  flightMode;
  uint32_t ms;
  uint32_t loopDtUs;
  uint32_t loopExecUs;
  uint32_t esekfUs;
  uint32_t missedPeriods;
  uint32_t logDropped;
  float    accel[3];
  float    gyro[3];
  float    accelNormMps2;  // raw accelerometer magnitude; verify free-fall detection in post
  float    rollDeg;
  float    pitchDeg;
  float    yawDeg;
  float    velocityNeu[3];
  float    positionNeu[3];
  float    gyroBias[3];
  float    accelBias[3];
  float    rateTargetRoll;    // outer-loop output (deg/s)
  float    rateTargetPitch;
  float    uRollDeg;          // servo command roll
  float    uPitchDeg;         // servo command pitch
  float    navRollCmdDeg;     // nav-commanded roll target (bank-to-turn)
  uint8_t  navWindState;      // 0=normal 1=penetration 2=level-hold
  float    gpsNisPos;         // NIS of last GPS position update (chi2, 3 dof)
  float    gpsNisVel;         // NIS of last GPS velocity update (chi2, 3 dof)
  float    leftServoDeg;
  float    rightServoDeg;
  float    morphServoDeg;
  float    tailServoDeg;
  uint16_t leftPwmUs;
  uint16_t rightPwmUs;
  uint16_t morphPwmUs;
  uint16_t tailPwmUs;
  bool     gpsFix;
  uint8_t  gpsSatellites;
  uint8_t  freeFallCount;  // counter value at log time (debug)
  uint8_t  approachCount;  // M3→M4 confirmation counter
  double   gpsLatitudeDeg;
  double   gpsLongitudeDeg;
  float    gpsAltitudeM;
  float    gpsSAccMps;
  float    gpsVelocityNed[3];
};

// ========================= Non-blocking logger queue =========================

static const uint8_t QUEUE_DEPTH = 24;
static ControlRecord               recordPool[QUEUE_DEPTH];
static rtos::Queue<ControlRecord, QUEUE_DEPTH> filledQueue;
static rtos::Queue<ControlRecord, QUEUE_DEPTH> freeQueue;
static rtos::Thread loggerThread;
static rtos::Mutex  serialMutex;

static void safeSerialPrintln(const __FlashStringHelper *s) {
  serialMutex.lock();
  Serial.println(s);
  serialMutex.unlock();
}

// ========================= Global state =========================

static Servo servoLeft;
static Servo servoRight;
static Servo servoMorph;
static Servo servoTail;

static ImuSample  imu   = {};
static GpsSample  gps   = {};
static ESEKFState esekf = {};

static float   gyroCalibration[3] = {};
static bool    gpsOriginSet       = false;
static double  gpsOriginLatDeg    = 0.0;
static double  gpsOriginLonDeg    = 0.0;
static float   gpsOriginAltM      = 0.0f;
static uint8_t gpsOriginGoodCount = 0;
static bool    gpsSosSent         = false; // true after UBX-UPD-SOS backup is sent

static float rollRad  = 0.0f;
static float pitchRad = 0.0f;
static float yawRad   = 0.0f;

// Mission state
static FlightMode flightMode       = MODE_CARRIED;
static uint32_t   modeStartUs      = 0;
static float      modeElapsedS     = 0.0f;
static uint8_t    freeFallCount    = 0;   // consecutive frames below FREE_FALL_THRESHOLD
static uint8_t    approachCount    = 0;   // consecutive frames inside approach zone
static float      morphDeployStart = MORPH_FOLD_DEG;
static float      heliVdFilt       = 0.0f;

// PID state (M3)
static float pidRateIntRoll     = 0.0f;
static float pidRateIntPitch    = 0.0f;
static float pidRateTargetRoll  = 0.0f;
static float pidRateTargetPitch = 0.0f;
static float uRollDeg           = 0.0f;
static float uPitchDeg          = 0.0f;

// Navigation state exposed for logging (written by navRollTargetDeg()).
// Declared here (not in mission.ino) because logger.ino precedes mission.ino
// in the Arduino build's alphabetical file concatenation.
static float        navRollCmdDeg = 0.0f;
static NavWindState navWindState  = NAV_WIND_NORMAL;

// NIS (Normalized Innovation Squared) of the latest GPS update, written by
// updateEsekfWithGps(). Approximate chi-square with 3 dof (sequential scalar
// updates); consistent filter → mean ≈ 3, 95% of samples below 7.81.
// Sustained values far above that = filter overconfident or GPS degraded.
static float gpsNisPos = 0.0f;
static float gpsNisVel = 0.0f;

// Servo output state
static float    leftServoDeg  = WING_FOLD_LEFT_DEG;
static float    rightServoDeg = WING_FOLD_RIGHT_DEG;
static float    morphServoDeg = MORPH_FOLD_DEG;
static float    tailServoDeg  = TAIL_HOLD_DEG;
static uint16_t leftPwmUs  = 1500;
static uint16_t rightPwmUs = 1500;
static uint16_t morphPwmUs = 500;
static uint16_t tailPwmUs  = 1500;

static bool     imuFaultLocked  = false;
static uint32_t nextLoopUs      = 0;
static uint32_t lastLoopUs      = 0;
static uint32_t nextLogUs       = 0;
static uint32_t logClockStartMs = 0;
static bool     logWindowOpen   = false;
static bool     logWindowDone   = false;
static bool     logStopQueued   = false;

// Performance counters (written by Core 0, readable by Core 1 for status prints).
static volatile uint32_t loopCount         = 0;
static volatile uint32_t missedPeriodCount = 0;
static volatile uint32_t logDroppedCount   = 0;
static volatile uint32_t maxLoopDtUs       = 0;
static volatile uint32_t maxLoopExecUs     = 0;
static volatile uint32_t maxEsekfUs        = 0;
static volatile uint32_t gpsEpochCount     = 0;
static volatile uint32_t esekfResetCount   = 0;

// GPS date shared between Core 0 (writer: handleNavPvt) and Core 1 logger (reader).
// g_gpsDateValid is committed last so Core 1 never reads a half-written month/day pair.
static volatile uint8_t g_gpsMonth     = 0;
static volatile uint8_t g_gpsDay       = 0;
static volatile bool    g_gpsDateValid = false;

// ESEKF work matrices (only used inside predictEsekf; kept global to avoid stack pressure).
static float phiMat[ESEKF_N][ESEKF_N];
static float tempMat[ESEKF_N][ESEKF_N];
static float covarianceNext[ESEKF_N][ESEKF_N];

// ========================= Math helpers =========================

static float sqf(float x) { return x * x; }

static float clampfLocal(float x, float lo, float hi) {
  if (x < lo) return lo;
  if (x > hi) return hi;
  return x;
}

static float wrapPi(float x) {
  return x - 2.0f * PI * floorf((x + PI) / (2.0f * PI));
}

static float deadband(float x, float band) {
  if (fabsf(x) <= band) return 0.0f;
  return x > 0.0f ? x - band : x + band;
}

static const char *modeName(FlightMode m) {
  switch (m) {
    case MODE_CARRIED:      return "M0_carried";
    case MODE_FREE_FALL:    return "M1_free_fall";
    case MODE_DEPLOYING:    return "M2_deploying";
    case MODE_GLIDE:        return "M3_glide";
    case MODE_APPROACH:     return "M4_approach";
    case MODE_HELI_DESCENT: return "M5_heli_descent";
    default:                return "unknown";
  }
}

// Filename auto-generated from GPS date (MM_DD_xx.CSV).
// Falls back to NOFIX_xx.CSV if GPS date unavailable within 60 s.
static void makeLogFilename(char *out, size_t sz, int idx) {
  if (g_gpsDateValid) {
    snprintf(out, sz, "%02u_%02u_%02d.CSV",
             (unsigned)g_gpsMonth, (unsigned)g_gpsDay, idx);
  } else {
    snprintf(out, sz, "NOFIX_%02d.CSV", idx);
  }
}

static uint32_t recordStartMs() {
  return (uint32_t)(RECORD_START_S * 1000.0f + 0.5f);
}
static uint32_t recordEndMs() {
  return (uint32_t)(RECORD_END_S * 1000.0f + 0.5f);
}

// ========================= Setup =========================

void setup() {
  Serial.begin(SERIAL_BAUD);
  const uint32_t t0 = millis();
  while (!Serial && (uint32_t)(millis()-t0) < SERIAL_WAIT_MS) delay(10);

  Serial1.begin(GPS_BAUD);
  gps.lastFusedTowMs = 0xFFFFFFFFUL;
  delay(300);
  configureM100();

  serialMutex.lock();
  Serial.println(F("[Core0] 719_GlideMission boot (wind-guard variant)"));
  Serial.println(F("[Core0] SD filename: auto from GPS date (MM_DD_xx.CSV)"));
  Serial.print(F("[Core0] free_fall_threshold_g="));
  Serial.println(FREE_FALL_THRESHOLD_MPS2 / G_MPS2, 2);
  Serial.print(F("[Core0] v_open_min_mps=")); Serial.print(V_OPEN_MIN_MPS, 1);
  Serial.print(F(" h_open_min_m="));          Serial.print(H_OPEN_MIN_M, 1);
  Serial.print(F(" h_force_open_m="));        Serial.println(H_FORCE_OPEN_M, 1);
  Serial.print(F("[Core0] approach_phases=")); Serial.println(ENABLE_APPROACH_PHASES);
  serialMutex.unlock();

  if (!IMU.begin()) {
    safeSerialPrintln(F("[Core0] FATAL: LSM6DSOX not detected."));
    while (true) delay(1000);
  }

  servoLeft.attach(SERVO_LEFT_PIN,  SERVO_MIN_US, SERVO_MAX_US);
  servoRight.attach(SERVO_RIGHT_PIN, SERVO_MIN_US, SERVO_MAX_US);
  servoMorph.attach(SERVO_MORPH_PIN, SERVO_MIN_US, SERVO_MAX_US);
  servoTail.attach(SERVO_TAIL_PIN,  SERVO_MIN_US, SERVO_MAX_US);
  leftServoDeg  = WING_FOLD_LEFT_DEG;
  rightServoDeg = WING_FOLD_RIGHT_DEG;
  morphServoDeg = MORPH_FOLD_DEG;
  tailServoDeg  = TAIL_HOLD_DEG;
  writeAllServos();

  loggerThread.start(loggerTask);
  delay(1500); // let servos settle before still-sensitive gyro calibration

  safeSerialPrintln(F("[Core0] Keep board still: gyro calibration."));
  bool calOk = false;
  for (uint8_t attempt = 0; attempt < 5 && !calOk; attempt++) {
    calOk = calibrateGyro();
    if (!calOk) {
      safeSerialPrintln(F("[Core0] Calibration disturbed — retrying."));
      delay(500);
    }
  }
  if (!calOk) {
    safeSerialPrintln(F("[Core0] FATAL: gyro calibration failed."));
    while (true) delay(1000);
  }

  serialMutex.lock();
  Serial.print(F("[Core0] gyro_bias_radps="));
  Serial.print(gyroCalibration[0], 7); Serial.print(',');
  Serial.print(gyroCalibration[1], 7); Serial.print(',');
  Serial.println(gyroCalibration[2], 7);
  serialMutex.unlock();

  ImuSample init = {};
  while (!readImu(init)) delay(10);
  resetEsekfFromAccel(init);

  flightMode      = MODE_CARRIED;
  modeStartUs     = micros();
  logClockStartMs = millis();
  lastLoopUs      = micros();
  nextLoopUs      = lastLoopUs + LOOP_DT_US;
  nextLogUs       = lastLoopUs;

  safeSerialPrintln(F("[Core0] Ready. Waiting for release (free-fall detection)."));
}

// ========================= Loop =========================

void loop() {
  pollGps();

  const uint32_t nowUs = micros();
  if ((int32_t)(nowUs - nextLoopUs) < 0) return;

  uint32_t elapsed = 0;
  while ((int32_t)(nowUs - nextLoopUs) >= 0) { nextLoopUs += LOOP_DT_US; elapsed++; }
  if (elapsed > 1) missedPeriodCount += elapsed - 1;

  const uint32_t loopDtUs = nowUs - lastLoopUs;
  lastLoopUs = nowUs;
  if (loopDtUs > maxLoopDtUs) maxLoopDtUs = loopDtUs;
  float dt = loopDtUs * 1.0e-6f;
  if (dt <= 0.f || dt > 0.1f) dt = DT_NOMINAL;

  if (imuFaultLocked) {
    // IMU lost: centre wing servos at 90° (symmetric neutral, no active control).
    // Do NOT fold — folding during M3/M4 would immediately crash the aircraft.
    // Morph and tail hold whatever was last commanded before the fault.
    leftServoDeg  = PID_NEUTRAL_DEG;
    rightServoDeg = PID_NEUTRAL_DEG;
    writeAllServos();
    maybeEnqueueLog(0, 0, 0);
    return;
  }

  const uint32_t execStart = micros();
  if (!readImu(imu)) {
    imuFaultLocked = true;
    safeSerialPrintln(F("[Core0] ERROR: IMU read failed."));
    maybeEnqueueLog(0, 0, 0);
    return;
  }

  if (!esekf.initialized) resetEsekfFromAccel(imu);

  const uint32_t esekfStart = micros();
  predictEsekf(imu, dt);
  updateEsekfWithAccelerometer(imu);
  updateEsekfWithGps();
  const uint32_t esekfUs = micros() - esekfStart;
  if (esekfUs > maxEsekfUs) maxEsekfUs = esekfUs;

  if (esekfHealthy()) {
    eulerFromQuaternion(esekf.q, rollRad, pitchRad, yawRad);
  } else {
    resetEsekfFromAccel(imu);
    eulerFromQuaternion(esekf.q, rollRad, pitchRad, yawRad);
    esekfResetCount++;
  }

  updateMission(dt);

  const uint32_t loopExecUs = micros() - execStart;
  if (loopExecUs > maxLoopExecUs) maxLoopExecUs = loopExecUs;
  loopCount++;

  maybeEnqueueLog(loopDtUs, loopExecUs, esekfUs);
}

// ############################################################################
// #### Begin: esekf.ino
// ############################################################################

// ========================= ESEKF: 15-state Error-State Kalman Filter =========================
//
// State vector (nominal):  q(4) v(3) p(3) bg(3) ba(3)
// Error-state vector dx:  dθ(3) dv(3) dp(3) dbg(3) dba(3)
//
// Prediction:  IMU integration at 80 Hz (predictEsekf)
// Updates:
//   - Accelerometer attitude leveling (updateEsekfWithAccelerometer)
//     Skipped when: |accel| outside 1g gate  OR  |omega| > rate gate
//   - GPS position + velocity (updateEsekfWithGps)
//     Uses adaptive velocity noise from M10 sAcc field
//
// Sequential scalar updates (scalarStateUpdate) keep covariance update O(N²)
// instead of O(N³) — necessary for a 15-state filter at 80 Hz on the RP2040.

// ========================= Quaternion math =========================

static void quatNormalize(float q[4]) {
  float n = sqrtf(q[0]*q[0] + q[1]*q[1] + q[2]*q[2] + q[3]*q[3]);
  if (n < 1.0e-8f) { q[0] = 1.f; q[1] = q[2] = q[3] = 0.f; return; }
  for (int i = 0; i < 4; i++) q[i] /= n;
}

static void quatMultiply(const float a[4], const float b[4], float out[4]) {
  out[0] = a[0]*b[0] - a[1]*b[1] - a[2]*b[2] - a[3]*b[3];
  out[1] = a[0]*b[1] + a[1]*b[0] + a[2]*b[3] - a[3]*b[2];
  out[2] = a[0]*b[2] - a[1]*b[3] + a[2]*b[0] + a[3]*b[1];
  out[3] = a[0]*b[3] + a[1]*b[2] - a[2]*b[1] + a[3]*b[0];
}

static void integrateQuaternion(float q[4], const float omega[3], float dt) {
  const float wn = sqrtf(omega[0]*omega[0] + omega[1]*omega[1] + omega[2]*omega[2]);
  float dq[4];
  if (wn < 1.0e-8f) {
    dq[0] = 1.f; dq[1] = 0.5f*omega[0]*dt;
    dq[2] = 0.5f*omega[1]*dt; dq[3] = 0.5f*omega[2]*dt;
  } else {
    const float ha = 0.5f * wn * dt;
    const float sc = sinf(ha) / wn;
    dq[0] = cosf(ha); dq[1] = sc*omega[0]; dq[2] = sc*omega[1]; dq[3] = sc*omega[2];
  }
  float qn[4]; quatMultiply(q, dq, qn);
  for (int i = 0; i < 4; i++) q[i] = qn[i];
  quatNormalize(q);
}

static void quaternionToRotation(const float q[4], float r[3][3]) {
  const float w=q[0], x=q[1], y=q[2], z=q[3];
  r[0][0]=1.f-2.f*(y*y+z*z); r[0][1]=2.f*(x*y-z*w); r[0][2]=2.f*(x*z+y*w);
  r[1][0]=2.f*(x*y+z*w); r[1][1]=1.f-2.f*(x*x+z*z); r[1][2]=2.f*(y*z-x*w);
  r[2][0]=2.f*(x*z-y*w); r[2][1]=2.f*(y*z+x*w); r[2][2]=1.f-2.f*(x*x+y*y);
}

static void eulerFromQuaternion(
    const float q[4], float &roll, float &pitch, float &yaw) {
  const float w=q[0], x=q[1], y=q[2], z=q[3];
  roll  = atan2f(2.f*(w*x+y*z), 1.f-2.f*(x*x+y*y));
  pitch = asinf(clampfLocal(2.f*(w*y-z*x), -1.f, 1.f));
  yaw   = atan2f(2.f*(w*z+x*y), 1.f-2.f*(y*y+z*z));
}

static void quaternionFromRollPitch(float roll, float pitch, float q[4]) {
  const float cr=cosf(0.5f*roll),  sr=sinf(0.5f*roll);
  const float cp=cosf(0.5f*pitch), sp=sinf(0.5f*pitch);
  q[0]=cp*cr; q[1]=cp*sr; q[2]=sp*cr; q[3]=-sp*sr;
  quatNormalize(q);
}

static void injectSmallAngle(float q[4], const float dtheta[3]) {
  float dq[4] = {1.f, 0.5f*dtheta[0], 0.5f*dtheta[1], 0.5f*dtheta[2]};
  quatNormalize(dq);
  float qn[4]; quatMultiply(q, dq, qn);
  for (int i = 0; i < 4; i++) q[i] = qn[i];
  quatNormalize(q);
}

// ========================= ESEKF core =========================

static void resetEsekfFromAccel(const ImuSample &s) {
  const float roll0  = atan2f(s.accel[1], s.accel[2]);
  const float pitch0 = atan2f(-s.accel[0],
      sqrtf(s.accel[1]*s.accel[1] + s.accel[2]*s.accel[2]));
  quaternionFromRollPitch(roll0, pitch0, esekf.q);
  for (int i = 0; i < 3; i++) {
    esekf.v[i]  = 0.f; esekf.p[i]  = 0.f;
    esekf.bg[i] = gyroCalibration[i]; esekf.ba[i] = 0.f;
  }
  for (int r = 0; r < ESEKF_N; r++)
    for (int c = 0; c < ESEKF_N; c++) esekf.P[r][c] = 0.f;
  for (int i = 0; i < 3; i++) {
    esekf.P[i][i]       = sqf(8.0f  * DEG_TO_RAD_F);  // attitude: 8°
    esekf.P[i+3][i+3]   = sqf(1.0f);                   // velocity: 1 m/s
    esekf.P[i+6][i+6]   = sqf(3.0f);                   // position: 3 m
    esekf.P[i+9][i+9]   = sqf(0.04f);                  // gyro bias
    esekf.P[i+12][i+12] = sqf(0.30f);                  // accel bias
  }
  esekf.initialized = true;
}

static void applyErrorState(const float dx[ESEKF_N]) {
  injectSmallAngle(esekf.q, dx);
  for (int i = 0; i < 3; i++) {
    esekf.v[i]  += dx[i+3];
    esekf.p[i]  += dx[i+6];
    esekf.bg[i] += dx[i+9];
    esekf.ba[i] += dx[i+12];
  }
}

static void symmetrizeAndFloor() {
  for (int r = 0; r < ESEKF_N; r++) {
    for (int c = r+1; c < ESEKF_N; c++) {
      const float avg = 0.5f * (esekf.P[r][c] + esekf.P[c][r]);
      esekf.P[r][c] = avg; esekf.P[c][r] = avg;
    }
    if (esekf.P[r][r] < 1.0e-10f) esekf.P[r][r] = 1.0e-10f;
  }
}

static bool esekfHealthy() {
  float qn = 0.f;
  for (int i = 0; i < 4; i++) {
    if (!isfinite(esekf.q[i])) return false;
    qn += esekf.q[i] * esekf.q[i];
  }
  if (qn < 0.5f || qn > 1.5f) return false;
  for (int i = 0; i < 3; i++) {
    if (!isfinite(esekf.v[i])  || !isfinite(esekf.p[i]) ||
        !isfinite(esekf.bg[i]) || !isfinite(esekf.ba[i])) return false;
  }
  for (int i = 0; i < ESEKF_N; i++)
    if (!isfinite(esekf.P[i][i]) || esekf.P[i][i] <= 0.f) return false;
  return true;
}

// ========================= ESEKF prediction (80 Hz) =========================

static void predictEsekf(const ImuSample &s, float dt) {
  float omega[3], ab[3];
  for (int i = 0; i < 3; i++) {
    omega[i] = s.gyro[i]  - esekf.bg[i];
    ab[i]    = s.accel[i] - esekf.ba[i];
  }

  integrateQuaternion(esekf.q, omega, dt);

  float R[3][3]; quaternionToRotation(esekf.q, R);
  float aw[3] = {
    R[0][0]*ab[0]+R[0][1]*ab[1]+R[0][2]*ab[2],
    R[1][0]*ab[0]+R[1][1]*ab[1]+R[1][2]*ab[2],
    R[2][0]*ab[0]+R[2][1]*ab[1]+R[2][2]*ab[2] - G_MPS2
  };
  for (int i = 0; i < 3; i++) {
    esekf.p[i] += esekf.v[i]*dt + 0.5f*aw[i]*dt*dt;
    esekf.v[i] += aw[i]*dt;
  }

  // Build state-transition matrix Φ (identity + first-order terms).
  for (int r = 0; r < ESEKF_N; r++)
    for (int c = 0; c < ESEKF_N; c++) phiMat[r][c] = (r == c) ? 1.f : 0.f;

  const float skewW[3][3] = {{0,-omega[2],omega[1]},{omega[2],0,-omega[0]},{-omega[1],omega[0],0}};
  const float skewA[3][3] = {{0,-ab[2],ab[1]},{ab[2],0,-ab[0]},{-ab[1],ab[0],0}};
  for (int r = 0; r < 3; r++) {
    for (int c = 0; c < 3; c++) {
      phiMat[r][c] += -skewW[r][c]*dt;
      float rsa = 0.f;
      for (int k = 0; k < 3; k++) rsa += R[r][k]*skewA[k][c];
      phiMat[r+3][c]   += -rsa*dt;
      phiMat[r+3][c+12] += -R[r][c]*dt;
    }
    phiMat[r][r+9]   += -dt;
    phiMat[r+6][r+3] +=  dt;
  }

  // P_next = Φ P Φᵀ + Q
  for (int r = 0; r < ESEKF_N; r++)
    for (int c = 0; c < ESEKF_N; c++) {
      float v = 0.f;
      for (int k = 0; k < ESEKF_N; k++) v += phiMat[r][k]*esekf.P[k][c];
      tempMat[r][c] = v;
    }
  for (int r = 0; r < ESEKF_N; r++)
    for (int c = 0; c < ESEKF_N; c++) {
      float v = 0.f;
      for (int k = 0; k < ESEKF_N; k++) v += tempMat[r][k]*phiMat[c][k];
      covarianceNext[r][c] = v;
    }

  const float qTh = sqf(GYRO_NOISE_RADPS)*dt;
  const float qV  = sqf(ACCEL_NOISE_MPS2)*dt;
  const float qP  = qV*dt*dt;
  const float qBg = sqf(GYRO_BIAS_RW_RADPS)*dt;
  const float qBa = sqf(ACCEL_BIAS_RW_MPS2)*dt;
  for (int i = 0; i < 3; i++) {
    covarianceNext[i][i]       += qTh;
    covarianceNext[i+3][i+3]   += qV;
    covarianceNext[i+6][i+6]   += qP;
    covarianceNext[i+9][i+9]   += qBg;
    covarianceNext[i+12][i+12] += qBa;
  }
  for (int r = 0; r < ESEKF_N; r++)
    for (int c = 0; c < ESEKF_N; c++) esekf.P[r][c] = covarianceNext[r][c];
  symmetrizeAndFloor();
}

// ========================= Scalar state update ===========================
//
// Updates a single observed state index with a scalar residual.
// K = P[:,idx] / (P[idx,idx] + R)
// dx = K * residual
// P_new = P - K * P[idx,:]
// Limit gate: reject if |residual| > limit (outlier protection).

static bool scalarStateUpdate(int idx, float residual, float R, float limit) {
  if (!isfinite(residual) || !isfinite(R) || fabsf(residual) > limit) return false;
  const float S = esekf.P[idx][idx] + R;
  if (S < 1.0e-9f) return false;
  float K[ESEKF_N], Hrow[ESEKF_N], dx[ESEKF_N];
  for (int i = 0; i < ESEKF_N; i++) {
    K[i]    = esekf.P[i][idx] / S;
    Hrow[i] = esekf.P[idx][i];
    dx[i]   = K[i] * residual;
  }
  applyErrorState(dx);
  for (int r = 0; r < ESEKF_N; r++)
    for (int c = 0; c < ESEKF_N; c++) esekf.P[r][c] -= K[r]*Hrow[c];
  symmetrizeAndFloor();
  return true;
}

// ========================= Accelerometer attitude update =================

static void updateEsekfWithAccelerometer(const ImuSample &s) {
  const float ax=s.accel[0], ay=s.accel[1], az=s.accel[2];
  const float norm = sqrtf(ax*ax + ay*ay + az*az);

  // Magnitude gate: only trust gravity vector when not accelerating.
  // Free fall (≈0g) and deployment loads both fall outside [0.82g, 1.18g]
  // automatically — no special-case code needed.
  if (norm < ACCEL_GATE_LOW_MPS2 || norm > ACCEL_GATE_HIGH_MPS2) return;

  // Rate gate: skip when rotating — centripetal acceleration would bias
  // the roll/pitch estimate. 0.25 rad/s ≈ 14°/s.
  // Validated by Kai Keller version: roll RMSE 14.9°→3.0° during morphing.
  const float gyroNorm = sqrtf(s.gyro[0]*s.gyro[0] +
                               s.gyro[1]*s.gyro[1] +
                               s.gyro[2]*s.gyro[2]);
  if (gyroNorm > ESEKF_LEVEL_RATE_GATE_RADPS) return;

  const float mRoll  = atan2f(ay, az);
  const float mPitch = atan2f(-ax, sqrtf(ay*ay + az*az));
  eulerFromQuaternion(esekf.q, rollRad, pitchRad, yawRad);
  scalarStateUpdate(0, wrapPi(mRoll  - rollRad),  sqf(ACCEL_LEVEL_NOISE_RAD), 25.f*DEG_TO_RAD_F);
  eulerFromQuaternion(esekf.q, rollRad, pitchRad, yawRad);
  scalarStateUpdate(1, wrapPi(mPitch - pitchRad), sqf(ACCEL_LEVEL_NOISE_RAD), 25.f*DEG_TO_RAD_F);
}

// ========================= GPS fusion =========================

// Convert GPS lat/lon/alt to local NEU frame relative to origin.
static void gpsToLocalNeu(float neu[3]) {
  static const double RE  = 6378137.0;
  static const double D2R = 0.017453292519943295;
  const double dlat  = (gps.latitudeDeg  - gpsOriginLatDeg) * D2R;
  const double dlon  = (gps.longitudeDeg - gpsOriginLonDeg) * D2R;
  const double lat0  = gpsOriginLatDeg * D2R;
  neu[0] = (float)(RE * dlat);
  neu[1] = (float)(RE * cos(lat0) * dlon);
  neu[2] = gps.altitudeM - gpsOriginAltM;
}

static void updateEsekfWithGps() {
  if (!gps.fix || !gps.fresh) return;
  gps.fresh = false;

  if (!gpsOriginSet) {
    if (gps.fixType >= 3 && gps.satellites >= GPS_ORIGIN_MIN_SATS &&
        gps.hAccM <= GPS_ORIGIN_MAX_HACC_M) {
      gpsOriginGoodCount++;
      if (gpsOriginGoodCount >= GPS_ORIGIN_STABLE_FIXES) {
        gpsOriginLatDeg = gps.latitudeDeg;
        gpsOriginLonDeg = gps.longitudeDeg;
        gpsOriginAltM   = gps.altitudeM;
        gpsOriginSet    = true;
        // Save GPS state to BBR so next power-on achieves a hot start.
        // Sent exactly once, right after the best-quality fix is locked.
        if (!gpsSosSent) { gpsSaveToBackupRam(); gpsSosSent = true; }
      }
    } else { gpsOriginGoodCount = 0; }
    return;
  }

  float neu[3]; gpsToLocalNeu(neu);
  const float hStd = fmaxf(gps.hAccM, GPS_POSITION_NOISE_FLOOR_M);
  const float vStd = fmaxf(gps.vAccM, GPS_VERTICAL_NOISE_FLOOR_M);
  // Adaptive velocity noise: use M10's reported sAcc, floored at
  // GPS_VELOCITY_NOISE_MPS. Tighter in open sky, looser when obstructed.
  const float velStd = fmaxf(gps.sAccMps, GPS_VELOCITY_NOISE_MPS);

  // NIS (Normalized Innovation Squared) accumulated across the sequential
  // scalar updates: sum of residual^2 / S with S = P[i][i] + R taken BEFORE
  // each update. Approximates the full-covariance chi-square (3 dof) —
  // standard filter-consistency metric, logged for offline validation.
  // Computed even for residuals the outlier gate rejects, so gate events
  // show up as NIS spikes in the log.
  const float vNeu[3] = {gps.velocityNed[0], gps.velocityNed[1], -gps.velocityNed[2]};
  float nisV = 0.f;
  for (int i = 0; i < 3; i++) {
    const float r_ = vNeu[i] - esekf.v[i];
    nisV += r_*r_ / (esekf.P[i+3][i+3] + sqf(velStd));
    scalarStateUpdate(i+3, r_, sqf(velStd), 25.f);
  }
  gpsNisVel = nisV;

  float nisP = 0.f;
  {
    const float rN = neu[0] - esekf.p[0];
    nisP += rN*rN / (esekf.P[6][6] + sqf(hStd));
    scalarStateUpdate(6, rN, sqf(hStd), 100.f);
    const float rE = neu[1] - esekf.p[1];
    nisP += rE*rE / (esekf.P[7][7] + sqf(hStd));
    scalarStateUpdate(7, rE, sqf(hStd), 100.f);
    const float rU = neu[2] - esekf.p[2];
    nisP += rU*rU / (esekf.P[8][8] + sqf(vStd));
    scalarStateUpdate(8, rU, sqf(vStd), 100.f);
  }
  gpsNisPos = nisP;
}

// ############################################################################
// #### Begin: gps.ino
// ############################################################################

// ========================= GPS: HGLRC M100 MINI (u-blox M10) =========================
//
// The M10 outputs UBX-NAV-PVT (class 0x01, id 0x07, 92-byte payload) only.
// Configuration via UBX-CFG-VALSET; the older CFG-MSG / CFG-RATE messages are
// not supported on the M10.
//
// Wiring:
//   GPS GND → board GND
//   GPS VCC → 3.3–5 V
//   GPS TX  → D1 (Serial1 RX)
//   GPS RX  → D0 (Serial1 TX)
//
// NAV-PVT byte offsets referenced in this file:
//   [0-3]   iTOW (ms)
//   [4-5]   year (U2 LE)        ← date fields
//   [6]     month (U1)
//   [7]     day   (U1)
//   [11]    valid flags: bit0=validDate, bit1=validTime
//   [20]    fixType
//   [21]    flags (bit0=gnssFixOK)
//   [23]    numSV
//   [24-27] lon (1e-7 deg, I4 LE)
//   [28-31] lat (1e-7 deg, I4 LE)
//   [36-39] hMSL (mm, I4 LE)
//   [40-43] hAcc (mm, U4 LE)
//   [44-47] vAcc (mm, U4 LE)
//   [48-51] velN (mm/s, I4 LE)
//   [52-55] velE (mm/s, I4 LE)
//   [56-59] velD (mm/s, I4 LE)
//   [68-71] sAcc (mm/s, U4 LE)  ← speed accuracy for adaptive noise

enum UbxState : uint8_t {
  UBX_SYNC1, UBX_SYNC2, UBX_CLASS, UBX_ID,
  UBX_LEN1, UBX_LEN2, UBX_PAYLOAD, UBX_CK_A, UBX_CK_B
};

static UbxState ubxState     = UBX_SYNC1;
static uint8_t  ubxClass     = 0;
static uint8_t  ubxId        = 0;
static uint16_t ubxLength    = 0;
static uint16_t ubxIndex     = 0;
static uint8_t  ubxChecksumA = 0;
static uint8_t  ubxChecksumB = 0;
static uint8_t  ubxPayload[100];

// ---- UBX low-level helpers ----

static void ubxChecksumAdd(uint8_t v) {
  ubxChecksumA += v;
  ubxChecksumB += ubxChecksumA;
}

static uint32_t readU32Le(const uint8_t *p) {
  return (uint32_t)p[0] | ((uint32_t)p[1] << 8) |
         ((uint32_t)p[2] << 16) | ((uint32_t)p[3] << 24);
}
static int32_t readI32Le(const uint8_t *p) {
  return (int32_t)readU32Le(p);
}

// ---- NAV-PVT handler ----

static void handleNavPvt() {
  if (ubxLength != 92) return;

  const uint32_t towMs = readU32Le(&ubxPayload[0]);

  // Parse date validity BEFORE the fix check.
  // validDate (byte 11 bit 0) can be set even without a 3D fix —
  // the M10's internal RTC may hold a valid date from a previous session.
  // g_gpsDateValid is written last so Core 1 (logger) never sees a
  // partial month/day pair.
  if (!g_gpsDateValid && (ubxPayload[11] & 0x01U)) {
    const uint8_t m = ubxPayload[6]; // month 1–12
    const uint8_t d = ubxPayload[7]; // day   1–31
    if (m >= 1 && m <= 12 && d >= 1 && d <= 31) {
      gps.month      = m;
      gps.day        = d;
      g_gpsMonth     = m;
      g_gpsDay       = d;
      g_gpsDateValid = true; // commit flag — written last
    }
  }

  gps.fixType    = ubxPayload[20];
  const uint8_t flags = ubxPayload[21];
  gps.satellites = ubxPayload[23];
  gps.fix = ((flags & 0x01U) != 0U) && gps.fixType >= 3;
  if (!gps.fix) { gps.fresh = false; return; }
  if (towMs == gps.lastFusedTowMs) return;

  gps.longitudeDeg   = readI32Le(&ubxPayload[24]) * 1.0e-7;
  gps.latitudeDeg    = readI32Le(&ubxPayload[28]) * 1.0e-7;
  gps.altitudeM      = readI32Le(&ubxPayload[36]) * 1.0e-3f;  // hMSL
  gps.hAccM          = readU32Le(&ubxPayload[40]) * 1.0e-3f;
  gps.vAccM          = readU32Le(&ubxPayload[44]) * 1.0e-3f;
  gps.velocityNed[0] = readI32Le(&ubxPayload[48]) * 1.0e-3f;
  gps.velocityNed[1] = readI32Le(&ubxPayload[52]) * 1.0e-3f;
  gps.velocityNed[2] = readI32Le(&ubxPayload[56]) * 1.0e-3f;
  // sAcc (byte 68): speed accuracy estimate in mm/s.
  // Used as adaptive velocity noise floor in the ESEKF. Tighter in open sky,
  // looser under obstruction — better than a fixed constant.
  gps.sAccMps = readU32Le(&ubxPayload[68]) * 1.0e-3f;

  gps.iTowMs         = towMs;
  gps.lastFusedTowMs = towMs;
  gps.receivedMs     = millis();
  gps.fresh          = true;
  gpsEpochCount++;
}

static void handleUbxPacket() {
  if (ubxClass == 0x01 && ubxId == 0x07) handleNavPvt();
}

// ---- UBX byte-level state machine ----

static void parseUbxByte(uint8_t v) {
  switch (ubxState) {
    case UBX_SYNC1:
      if (v == 0xB5) ubxState = UBX_SYNC2;
      break;
    case UBX_SYNC2:
      ubxState = (v == 0x62) ? UBX_CLASS : UBX_SYNC1;
      break;
    case UBX_CLASS:
      ubxClass = v; ubxChecksumA = 0; ubxChecksumB = 0;
      ubxChecksumAdd(v); ubxState = UBX_ID;
      break;
    case UBX_ID:
      ubxId = v; ubxChecksumAdd(v); ubxState = UBX_LEN1;
      break;
    case UBX_LEN1:
      ubxLength = v; ubxChecksumAdd(v); ubxState = UBX_LEN2;
      break;
    case UBX_LEN2:
      ubxLength |= ((uint16_t)v << 8); ubxChecksumAdd(v); ubxIndex = 0;
      ubxState = (ubxLength > sizeof(ubxPayload)) ? UBX_SYNC1
               : (ubxLength == 0)                  ? UBX_CK_A
               :                                     UBX_PAYLOAD;
      break;
    case UBX_PAYLOAD:
      ubxPayload[ubxIndex++] = v; ubxChecksumAdd(v);
      if (ubxIndex >= ubxLength) ubxState = UBX_CK_A;
      break;
    case UBX_CK_A:
      ubxState = (v == ubxChecksumA) ? UBX_CK_B : UBX_SYNC1;
      break;
    case UBX_CK_B:
      if (v == ubxChecksumB) handleUbxPacket();
      ubxState = UBX_SYNC1;
      break;
  }
}

// ---- UBX transmit helpers ----

static void sendUbx(uint8_t cls, uint8_t id,
                    const uint8_t *payload, uint16_t len) {
  uint8_t ca = 0, cb = 0;
  Serial1.write(0xB5); Serial1.write(0x62);
  const uint8_t hdr[4] = {cls, id, (uint8_t)(len & 0xFF), (uint8_t)(len >> 8)};
  for (uint8_t i = 0; i < 4; i++) { Serial1.write(hdr[i]); ca += hdr[i]; cb += ca; }
  for (uint16_t i = 0; i < len; i++) { Serial1.write(payload[i]); ca += payload[i]; cb += ca; }
  Serial1.write(ca); Serial1.write(cb);
  Serial1.flush();
}

static void sendValset(const uint8_t *kv, uint16_t kvLen) {
  uint8_t payload[32];
  payload[0] = 0x00; payload[1] = 0x01; // version=0, layer=RAM
  payload[2] = 0x00; payload[3] = 0x00;
  for (uint16_t i = 0; i < kvLen; i++) payload[4 + i] = kv[i];
  sendUbx(0x06, 0x8A, payload, (uint16_t)(4 + kvLen));
  delay(20);
}

// ---- M10 receiver configuration (called once in setup) ----

static void configureM100() {
  // Enable UBX output on UART1; disable NMEA to reduce serial load.
  const uint8_t protocols[] = {
    0x01, 0x00, 0x74, 0x10, 0x01,  // CFG-UART1OUTPROT-UBX  = 1
    0x02, 0x00, 0x74, 0x10, 0x00   // CFG-UART1OUTPROT-NMEA = 0
  };
  sendValset(protocols, sizeof(protocols));

  // Enable NAV-PVT at 1 message per measurement epoch.
  const uint8_t pvtRate[] = {
    0x07, 0x00, 0x91, 0x20, 0x01   // CFG-MSGOUT-UBX_NAV_PVT_UART1 = 1
  };
  sendValset(pvtRate, sizeof(pvtRate));

  // Set measurement rate to GPS_MEASUREMENT_PERIOD_MS (100 ms = 10 Hz).
  const uint8_t measRate[] = {
    0x01, 0x00, 0x21, 0x30,
    (uint8_t)(GPS_MEASUREMENT_PERIOD_MS & 0xFF),
    (uint8_t)(GPS_MEASUREMENT_PERIOD_MS >> 8)
  };
  sendValset(measRate, sizeof(measRate));
}

// ---- Hot-start backup ----
//
// UBX-UPD-SOS (class 0x09, id 0x14), command 0 = create backup.
// Saves the current position, time, and satellite ephemeris into the M10's
// battery-backed RAM (BBR). On the next cold power-cycle the receiver reads
// this snapshot and hot-starts in 5–15 s instead of 2–5 minutes.
//
// Called once by updateEsekfWithGps() immediately after GPS origin is locked,
// ensuring we have a high-quality fix to snapshot.
static void gpsSaveToBackupRam() {
  const uint8_t payload[4] = {0x00, 0x00, 0x00, 0x00}; // cmd=0
  sendUbx(0x09, 0x14, payload, sizeof(payload));
  safeSerialPrintln(F("[GPS] UBX-UPD-SOS backup sent (hot-start next boot)."));
}

// ---- Main GPS poll (called every loop iteration from Core 0) ----

static void pollGps() {
  while (Serial1.available() > 0) {
    gps.bytesSeen = true;
    parseUbxByte((uint8_t)Serial1.read());
  }
  // Invalidate fix if no packet received within GPS_FIX_STALE_MS.
  if (gps.fix && (uint32_t)(millis() - gps.receivedMs) > GPS_FIX_STALE_MS) {
    gps.fix   = false;
    gps.fresh = false;
  }
}

// ############################################################################
// #### Begin: imu.ino
// ############################################################################

// ========================= IMU: LSM6DSOX =========================
//
// The LSM6DSOX is accessed via the Arduino_LSM6DSOX library.
// readImu() polls until both accel and gyro are available;
// calibrateGyro() collects CAL_SAMPLES readings and computes bias.
//
// Axis mapping (library → body frame):
//   accel[0] = X forward,  accel[1] = Y left,  accel[2] = Z up   (m/s²)
//   gyro[0]  = roll rate,  gyro[1]  = pitch rate, gyro[2] = yaw rate (rad/s)

static bool readImu(ImuSample &s) {
  const uint32_t t0 = micros();
  while (!IMU.accelerationAvailable() || !IMU.gyroscopeAvailable()) {
    if ((uint32_t)(micros() - t0) > 8000UL) { s.valid = false; return false; }
  }
  float axG, ayG, azG, gxDps, gyDps, gzDps;
  IMU.readAcceleration(axG, ayG, azG);
  IMU.readGyroscope(gxDps, gyDps, gzDps);
  s.accel[0] = axG * G_MPS2;
  s.accel[1] = ayG * G_MPS2;
  s.accel[2] = azG * G_MPS2;
  s.gyro[0]  = gxDps * DEG_TO_RAD_F;
  s.gyro[1]  = gyDps * DEG_TO_RAD_F;
  s.gyro[2]  = gzDps * DEG_TO_RAD_F;
  s.valid    = true;
  return true;
}

// Collects CAL_SAMPLES static samples and fits a mean gyro bias.
// Returns false if:
//   - fewer than half the samples were usable (IMU timeout)
//   - accelerometer magnitude is outside 1g gate (board was moved)
//   - any gyro axis bias exceeds 5·GYRO_NOISE_RADPS (sensor fault)
//   - gyro variance exceeds 3·GYRO_NOISE_RADPS² (vibration present)
static bool calibrateGyro() {
  float sum[3] = {}, sumSq[3] = {};
  uint16_t good = 0;
  for (uint16_t i = 0; i < CAL_SAMPLES; i++) {
    ImuSample s = {};
    if (readImu(s)) {
      const float aN = sqrtf(s.accel[0]*s.accel[0] +
                             s.accel[1]*s.accel[1] +
                             s.accel[2]*s.accel[2]);
      if (aN < ACCEL_GATE_LOW_MPS2 || aN > ACCEL_GATE_HIGH_MPS2) return false;
      for (int a = 0; a < 3; a++) {
        sum[a]   += s.gyro[a];
        sumSq[a] += s.gyro[a] * s.gyro[a];
      }
      good++;
    }
    delay(CAL_DT_MS);
  }
  if (good < CAL_SAMPLES / 2) return false;
  for (int a = 0; a < 3; a++) {
    gyroCalibration[a] = sum[a] / (float)good;
    const float var = sumSq[a] / (float)good - sqf(gyroCalibration[a]);
    if (fabsf(gyroCalibration[a]) > 5.0f * GYRO_NOISE_RADPS) return false;
    if (var > sqf(3.0f * GYRO_NOISE_RADPS)) return false;
  }
  return true;
}

// ############################################################################
// #### Begin: logger.ino
// ############################################################################

// ========================= Logger thread (Core 1) =========================
//
// Architecture: Core 0 (main loop) fills ControlRecord structs from a free
// pool and posts them to filledQueue. Core 1 drains filledQueue and writes
// CSV rows to the SD card. freeQueue recycles slots back to Core 0.
//
// File naming: waits up to 60 s for Core 0 to deliver a GPS date (month/day)
// via g_gpsDateValid. If GPS provides a date in time, the file is named
// MM_DD_xx.CSV automatically — no manual LOG_TAG needed. If GPS date is not
// available within 60 s, NOFIX_xx.CSV is used as a fallback.
//
// SD writes are slow (~1 ms/row) so logging runs at SD_LOG_HZ (20 Hz)
// while control runs at LOOP_HZ (80 Hz). The queue absorbs the rate mismatch.
// Flush every SD_FLUSH_EVERY_N rows to reduce data loss on crash.

// ---- CSV header ----

static void writeCsvHeader(Print &out) {
  out.println(F(
    "ms,mode_id,mode_name,loop_dt_us,loop_exec_us,esekf_us,"
    "missed,log_dropped,"
    "ax,ay,az,gx,gy,gz,accel_norm_mps2,"
    "roll_deg,pitch_deg,yaw_deg,"
    "vn,ve,vu,pn,pe,pu,bgx,bgy,bgz,bax,bay,baz,"
    "rate_tgt_roll,rate_tgt_pitch,u_roll_deg,u_pitch_deg,"
    "nav_roll_tgt_deg,nav_wind_state,gps_nis_pos,gps_nis_vel,"
    "left_deg,right_deg,morph_deg,tail_deg,"
    "left_pwm,right_pwm,morph_pwm,tail_pwm,"
    "free_fall_count,approach_count,"
    "gps_fix,gps_sats,gps_lat_deg,gps_lon_deg,gps_alt_m,gps_sacc_mps,"
    "gps_vn,gps_ve,gps_vd"
  ));
}

// ---- CSV row writer ----

static void writeRecord(Print &out, const ControlRecord &r) {
  out.print(r.ms);                out.print(',');
  out.print(r.flightMode);        out.print(',');
  out.print(modeName((FlightMode)r.flightMode)); out.print(',');
  out.print(r.loopDtUs);          out.print(',');
  out.print(r.loopExecUs);        out.print(',');
  out.print(r.esekfUs);           out.print(',');
  out.print(r.missedPeriods);     out.print(',');
  out.print(r.logDropped);        out.print(',');
  for (int i = 0; i < 3; i++) { out.print(r.accel[i], 5); out.print(','); }
  for (int i = 0; i < 3; i++) { out.print(r.gyro[i],  6); out.print(','); }
  out.print(r.accelNormMps2, 4);  out.print(',');
  out.print(r.rollDeg,  3);       out.print(',');
  out.print(r.pitchDeg, 3);       out.print(',');
  out.print(r.yawDeg,   3);       out.print(',');
  for (int i = 0; i < 3; i++) { out.print(r.velocityNeu[i], 4); out.print(','); }
  for (int i = 0; i < 3; i++) { out.print(r.positionNeu[i], 4); out.print(','); }
  for (int i = 0; i < 3; i++) { out.print(r.gyroBias[i],    7); out.print(','); }
  for (int i = 0; i < 3; i++) { out.print(r.accelBias[i],   6); out.print(','); }
  out.print(r.rateTargetRoll,  3); out.print(',');
  out.print(r.rateTargetPitch, 3); out.print(',');
  out.print(r.uRollDeg,   3);      out.print(',');
  out.print(r.uPitchDeg,  3);      out.print(',');
  out.print(r.navRollCmdDeg, 3);   out.print(',');
  out.print(r.navWindState);       out.print(',');
  out.print(r.gpsNisPos, 3);       out.print(',');
  out.print(r.gpsNisVel, 3);       out.print(',');
  out.print(r.leftServoDeg,  2);   out.print(',');
  out.print(r.rightServoDeg, 2);   out.print(',');
  out.print(r.morphServoDeg, 2);   out.print(',');
  out.print(r.tailServoDeg,  2);   out.print(',');
  out.print(r.leftPwmUs);          out.print(',');
  out.print(r.rightPwmUs);         out.print(',');
  out.print(r.morphPwmUs);         out.print(',');
  out.print(r.tailPwmUs);          out.print(',');
  out.print(r.freeFallCount);      out.print(',');
  out.print(r.approachCount);      out.print(',');
  out.print(r.gpsFix ? 1 : 0);    out.print(',');
  if (r.gpsFix) {
    out.print(r.gpsSatellites);         out.print(',');
    out.print(r.gpsLatitudeDeg,  7);    out.print(',');
    out.print(r.gpsLongitudeDeg, 7);    out.print(',');
    out.print(r.gpsAltitudeM,    3);    out.print(',');
    out.print(r.gpsSAccMps,      3);    out.print(',');
    out.print(r.gpsVelocityNed[0], 3);  out.print(',');
    out.print(r.gpsVelocityNed[1], 3);  out.print(',');
    out.println(r.gpsVelocityNed[2], 3);
  } else {
    out.println(F(",,,,,,,"));
  }
}

// ---- Periodic serial status (called from Core 1 every 2 s) ----

static void printStatus() {
  serialMutex.lock();
  Serial.print(F("STAT mode="));
  Serial.print(modeName(flightMode));
  Serial.print(F(" agl="));
  Serial.print(esekf.p[2], 1);
  Serial.print(F("m spd="));
  Serial.print(sqrtf(esekf.v[0]*esekf.v[0] +
                     esekf.v[1]*esekf.v[1] +
                     esekf.v[2]*esekf.v[2]), 1);
  Serial.print(F("m/s gps_fix="));
  Serial.print(gps.fix ? 1 : 0);
  Serial.print(F(" ff_cnt="));
  Serial.print(freeFallCount);
  Serial.print(F(" t="));
  Serial.print((millis() - logClockStartMs) * 0.001f, 1);
  Serial.println('s');
  serialMutex.unlock();
}

// ---- Logger thread (Core 1 entry point) ----

static void loggerTask() {
  // Seed the free pool so Core 0 can start queuing records immediately.
  for (uint8_t i = 0; i < QUEUE_DEPTH; i++) freeQueue.put(&recordPool[i], osWaitForever);

  pinMode(SD_CS_PIN, OUTPUT);
  digitalWrite(SD_CS_PIN, HIGH);
  SPI.begin();
  delay(100);

  bool sdReady = false;
  for (int retry = 0; retry < 5 && !sdReady; retry++) {
    sdReady = SD.begin(SD_CS_PIN);
    if (!sdReady) delay(400);
  }

  File logFile;
  if (!sdReady) {
    safeSerialPrintln(F("[Core1] ERROR: SD.begin failed."));
  } else {
    // Wait up to 60 s for Core 0 to deliver a valid GPS date from NAV-PVT.
    // The aircraft is on the ground being carried up; GPS should lock well before launch.
    // If it times out, NOFIX_xx.CSV is used as a fallback — still useful for debugging.
    {
      const uint32_t dateWaitStart = millis();
      while (!g_gpsDateValid && (millis() - dateWaitStart) < 60000U) {
        osDelay(200);
      }
      if (g_gpsDateValid) {
        serialMutex.lock();
        Serial.print(F("[Core1] GPS date: "));
        Serial.print((unsigned)g_gpsMonth);
        Serial.print('/');
        Serial.println((unsigned)g_gpsDay);
        serialMutex.unlock();
      } else {
        safeSerialPrintln(F("[Core1] GPS date timeout — using NOFIX filename."));
      }
    }

    char fn[16];
    for (int i = 0; i < 100; i++) {
      makeLogFilename(fn, sizeof(fn), i);
      if (!SD.exists(fn)) { logFile = SD.open(fn, FILE_WRITE); break; }
    }
    if (logFile) {
      writeCsvHeader(logFile);
      logFile.flush();
      serialMutex.lock();
      Serial.print(F("[Core1] Logging to: "));
      Serial.println(logFile.name());
      serialMutex.unlock();
    } else {
      sdReady = false;
      safeSerialPrintln(F("[Core1] ERROR: cannot create log file."));
    }
  }

  uint32_t rowCount    = 0;
  uint32_t lastStatusMs = millis();

  while (true) {
    osEvent ev = filledQueue.get(100);
    if (ev.status == osEventMessage) {
      ControlRecord *rec = reinterpret_cast<ControlRecord*>(ev.value.p);
      if (rec->kind == RECORD_STOP) {
        if (sdReady && logFile) {
          logFile.print(F("# stop=time_end\n# records="));
          logFile.println(rowCount);
          logFile.flush();
          logFile.close();
          safeSerialPrintln(F("[Core1] Log closed."));
        }
        freeQueue.put(rec, osWaitForever);
        sdReady = false;
      } else {
        if (sdReady && logFile) {
          writeRecord(logFile, *rec);
          rowCount++;
          if ((rowCount % SD_FLUSH_EVERY_N) == 0) logFile.flush();
          if (logFile.getWriteError()) {
            logFile.print(F("# stop=write_error\n# records="));
            logFile.println(rowCount);
            logFile.flush();
            logFile.close();
            sdReady = false;
            safeSerialPrintln(F("[Core1] ERROR: SD write error."));
          }
        }
        freeQueue.put(rec, osWaitForever);
      }
    }
    if ((uint32_t)(millis() - lastStatusMs) >= 2000) {
      printStatus();
      lastStatusMs = millis();
    }
  }
}

// ---- Record builder (called from Core 0) ----

static ControlRecord makeRecord(
    uint32_t logMs, uint32_t loopDtUs,
    uint32_t loopExecUs, uint32_t esekfUs) {
  ControlRecord r = {};
  r.kind          = RECORD_DATA;
  r.flightMode    = (uint8_t)flightMode;
  r.ms            = logMs;
  r.loopDtUs      = loopDtUs;
  r.loopExecUs    = loopExecUs;
  r.esekfUs       = esekfUs;
  r.missedPeriods = missedPeriodCount;
  r.logDropped    = logDroppedCount;

  for (int i = 0; i < 3; i++) {
    r.accel[i]          = imu.accel[i];
    r.gyro[i]           = imu.gyro[i];
    r.velocityNeu[i]    = esekf.v[i];
    r.positionNeu[i]    = esekf.p[i];
    r.gyroBias[i]       = esekf.bg[i];
    r.accelBias[i]      = esekf.ba[i];
    r.gpsVelocityNed[i] = gps.velocityNed[i];
  }
  r.accelNormMps2   = sqrtf(imu.accel[0]*imu.accel[0] +
                             imu.accel[1]*imu.accel[1] +
                             imu.accel[2]*imu.accel[2]);
  r.rollDeg         = rollRad  * RAD_TO_DEG_F;
  r.pitchDeg        = pitchRad * RAD_TO_DEG_F;
  r.yawDeg          = yawRad   * RAD_TO_DEG_F;
  r.rateTargetRoll  = pidRateTargetRoll;
  r.rateTargetPitch = pidRateTargetPitch;
  r.uRollDeg        = uRollDeg;
  r.uPitchDeg       = uPitchDeg;
  r.navRollCmdDeg   = navRollCmdDeg;
  r.navWindState    = (uint8_t)navWindState;
  r.gpsNisPos       = gpsNisPos;
  r.gpsNisVel       = gpsNisVel;
  r.leftServoDeg    = leftServoDeg;
  r.rightServoDeg   = rightServoDeg;
  r.morphServoDeg   = morphServoDeg;
  r.tailServoDeg    = tailServoDeg;
  r.leftPwmUs       = leftPwmUs;
  r.rightPwmUs      = rightPwmUs;
  r.morphPwmUs      = morphPwmUs;
  r.tailPwmUs       = tailPwmUs;
  r.freeFallCount   = freeFallCount;
  r.approachCount   = approachCount;
  r.gpsFix          = gps.fix;
  r.gpsSatellites   = gps.satellites;
  r.gpsLatitudeDeg  = gps.latitudeDeg;
  r.gpsLongitudeDeg = gps.longitudeDeg;
  r.gpsAltitudeM    = gps.altitudeM;
  r.gpsSAccMps      = gps.sAccMps;
  return r;
}

static bool takeFreeRecord(ControlRecord *&slot) {
  osEvent ev = freeQueue.get(0);
  if (ev.status != osEventMessage) return false;
  slot = reinterpret_cast<ControlRecord*>(ev.value.p);
  return true;
}

static void maybeEnqueueLog(
    uint32_t loopDtUs, uint32_t loopExecUs, uint32_t esekfUs) {
  if (logWindowDone) {
    if (!logStopQueued) {
      ControlRecord *sr = nullptr;
      if (takeFreeRecord(sr)) {
        *sr = {}; sr->kind = RECORD_STOP;
        if (filledQueue.put(sr, 0) == osOK) logStopQueued = true;
        else freeQueue.put(sr, osWaitForever);
      }
    }
    return;
  }
  const uint32_t elapsedMs = millis() - logClockStartMs;
  if (elapsedMs < recordStartMs()) return;
  if (!logWindowOpen) { logWindowOpen = true; nextLogUs = micros(); }
  if (elapsedMs >= recordEndMs()) {
    logWindowDone = true;
    safeSerialPrintln(F("[Core0] Log window closed."));
    return;
  }
  const uint32_t nowUs = micros();
  if ((int32_t)(nowUs - nextLogUs) < 0) return;
  while ((int32_t)(nowUs - nextLogUs) >= 0) nextLogUs += SD_LOG_DT_US;

  ControlRecord *slot = nullptr;
  if (!takeFreeRecord(slot)) { logDroppedCount++; return; }
  *slot = makeRecord(elapsedMs - recordStartMs(), loopDtUs, loopExecUs, esekfUs);
  if (filledQueue.put(slot, 0) != osOK) {
    logDroppedCount++;
    freeQueue.put(slot, osWaitForever);
  }
}

// ############################################################################
// #### Begin: mission.ino
// ############################################################################

// ========================= Servo output =========================

static int pwmFromDeg(float deg) {
  deg = clampfLocal(deg, SERVO_MIN_DEG, SERVO_MAX_DEG);
  const float frac = (deg - SERVO_MIN_DEG) / (SERVO_MAX_DEG - SERVO_MIN_DEG);
  return (int)lroundf(SERVO_MIN_US + frac*(SERVO_MAX_US - SERVO_MIN_US));
}

static void writeAllServos() {
  // Slew limiter: each channel moves toward its commanded angle at no more
  // than SERVO_SLEW_LIMIT_DPS. First call passes through unlimited so the
  // boot-time fold positioning is immediate. dt is capped at 50 ms so a
  // stalled loop cannot produce a giant step on resume.
  static bool     slewInit = false;
  static float    slewDeg[4];
  static uint32_t slewLastUs = 0;

  float tgt[4] = {leftServoDeg, rightServoDeg, morphServoDeg, tailServoDeg};
  const uint32_t nowUs = micros();
  if (!slewInit) {
    for (int i = 0; i < 4; i++) slewDeg[i] = tgt[i];
    slewInit = true;
  } else {
    float dtS = (nowUs - slewLastUs) * 1.0e-6f;
    if (dtS > 0.05f) dtS = 0.05f;
    const float maxStep = SERVO_SLEW_LIMIT_DPS * dtS;
    for (int i = 0; i < 4; i++) {
      const float d = tgt[i] - slewDeg[i];
      if      (d >  maxStep) tgt[i] = slewDeg[i] + maxStep;
      else if (d < -maxStep) tgt[i] = slewDeg[i] - maxStep;
      slewDeg[i] = tgt[i];
    }
  }
  slewLastUs = nowUs;

  leftPwmUs  = (uint16_t)pwmFromDeg(tgt[0]);
  rightPwmUs = (uint16_t)pwmFromDeg(tgt[1]);
  morphPwmUs = (uint16_t)pwmFromDeg(tgt[2]);
  tailPwmUs  = (uint16_t)pwmFromDeg(tgt[3]);
  servoLeft.writeMicroseconds(leftPwmUs);
  servoRight.writeMicroseconds(rightPwmUs);
  servoMorph.writeMicroseconds(morphPwmUs);
  servoTail.writeMicroseconds(tailPwmUs);
}

// ========================= GPS navigation (bank-to-turn) =========================
//
// Third (outermost) guidance layer on top of the cascade PID:
//   heading error = bearing(to target) - ground track(from ESEKF velocity)
//   roll target   = clamp(NAV_KP · heading error, ±NAV_MAX_BANK_DEG)
//
// Ground track comes from ESEKF horizontal velocity (GPS-fused), NOT from
// yaw — yaw is unobservable without a magnetometer and drifts freely.
// Falls back to wings-level (ROLL_TARGET_DEG) whenever navigation
// cannot be trusted: no GPS origin, no fix, too slow, or already close.
//
// Wind-response state machine (navWindState lives in the main .ino because
// logger.ino needs it and precedes this file in the build):
//
//   NORMAL ──(saturated turn + losing ground for NAV_STUCK_TURN_MS)──►
//     PENETRATION (partial sweep raises airspeed, steering continues)
//       ──(closing > PENETRATION_EXIT_CLOSE_MPS)──► NORMAL
//       ──(still losing after PENETRATION_GIVEUP_MS)──► LEVEL_HOLD
//     LEVEL_HOLD (wings level, morph reopened, minimum sink)
//       ──(closing > NAV_RESUME_CLOSE_MPS)──► NORMAL
//
// If ENABLE_PENETRATION_MODE is 0, or AGL is below PENETRATION_MIN_AGL_M,
// the stuck turn goes straight to LEVEL_HOLD (original wind-guard behaviour).
static bool     navSatTurnLive    = false; // saturated no-progress turn in progress
static uint32_t navSatTurnStartMs = 0;
static uint32_t navWindStateMs    = 0;     // entry time of the current wind state

// Penetration is only meaningful while actively steering. If navigation
// becomes unavailable (GPS lost, arrived, too slow) while the sweep is
// engaged, reopen the wings — otherwise the state machine's exit checks
// are skipped and the aircraft would stay swept (high sink) indefinitely.
static void navAbortPenetrationIfActive() {
  if (navWindState == NAV_WIND_PENETRATION) {
    navWindState = NAV_WIND_NORMAL;
    safeSerialPrintln(F("[NAV] Navigation unavailable - penetration sweep reopened."));
  }
}

static float navRollTargetCompute() {
#if ENABLE_GPS_NAVIGATION
  if (!gpsOriginSet || !gps.fix) {
    navAbortPenetrationIfActive();
    return ROLL_TARGET_DEG;
  }

  const float dn = APPROACH_TARGET_N_M - esekf.p[0];
  const float de = APPROACH_TARGET_E_M - esekf.p[1];
  const float dist = sqrtf(dn*dn + de*de);
  if (dist < NAV_ARRIVAL_RADIUS_M) {
    navAbortPenetrationIfActive();
    return ROLL_TARGET_DEG;
  }

  const float groundSpeed = sqrtf(esekf.v[0]*esekf.v[0] + esekf.v[1]*esekf.v[1]);
  if (groundSpeed < NAV_MIN_GROUND_SPEED_MPS) {
    // Track angle untrustworthy at low ground speed, so no steering this
    // frame. Do NOT abort penetration here: passing through zero ground
    // speed is the EXPECTED transient while penetration builds airspeed
    // (blown-back → stopped → forward). Keep the sweep and let the give-up
    // timer decide; without this the sweep would reopen mid-transient and
    // the aircraft would oscillate between penetrating and drifting.
    if (navWindState == NAV_WIND_PENETRATION &&
        (uint32_t)(millis() - navWindStateMs) >= PENETRATION_GIVEUP_MS) {
      navWindState   = NAV_WIND_LEVEL_HOLD;
      navWindStateMs = millis();
      safeSerialPrintln(F("[NAV] Penetration failed - holding wings level."));
    }
    return ROLL_TARGET_DEG;
  }

  // Closing speed: projection of ground velocity onto the target direction.
  // Positive = approaching the target, negative = being pushed away.
  const float vClose = (esekf.v[0]*dn + esekf.v[1]*de) / dist;

  // Level hold: turning was declared futile even with penetration. Stay
  // wings-level (minimum sink) until we are genuinely closing again.
  if (navWindState == NAV_WIND_LEVEL_HOLD) {
    if (vClose > NAV_RESUME_CLOSE_MPS) {
      navWindState = NAV_WIND_NORMAL;
      safeSerialPrintln(F("[NAV] Closing on target again - navigation resumed."));
    } else {
      return ROLL_TARGET_DEG;
    }
  }

  // Penetration: sweep is engaged (morph handled in MODE_GLIDE), airspeed
  // is building. Keep steering — the extra speed is what restores turning
  // authority over the ground track.
  if (navWindState == NAV_WIND_PENETRATION) {
    if (vClose > PENETRATION_EXIT_CLOSE_MPS) {
      navWindState = NAV_WIND_NORMAL;
      safeSerialPrintln(F("[NAV] Penetration succeeded - back to normal glide."));
    } else if ((uint32_t)(millis() - navWindStateMs) >= PENETRATION_GIVEUP_MS) {
      navWindState   = NAV_WIND_LEVEL_HOLD;
      navWindStateMs = millis();
      safeSerialPrintln(F("[NAV] Penetration failed - holding wings level."));
      return ROLL_TARGET_DEG;
    }
    // fall through: continue steering while penetrating
  }

  const float bearingRad = atan2f(de, dn);                 // desired course (N=0, E=+90°)
  const float trackRad   = atan2f(esekf.v[1], esekf.v[0]); // current ground track
  const float hdgErrDeg  = wrapPi(bearingRad - trackRad) * RAD_TO_DEG_F;

  // Positive heading error (target right of track) → positive roll → right bank.
  // If the aircraft turns away from the target, negate NAV_KP_ROLL_PER_HDG_DEG.
  const float cmd = clampfLocal(NAV_KP_ROLL_PER_HDG_DEG * hdgErrDeg,
                                -NAV_MAX_BANK_DEG, NAV_MAX_BANK_DEG);

  // Stuck-turn detection (only from NORMAL): saturated bank AND still
  // losing ground. At 15° bank / ~10 m/s the heading changes ~15°/s, so 5 s
  // of saturated turning sweeps ~75° of heading. If closing speed never went
  // positive in that span, the wind beats our normal glide airspeed.
  const bool saturated = (fabsf(cmd) >= NAV_MAX_BANK_DEG - 0.1f);
  if (navWindState == NAV_WIND_NORMAL && saturated && vClose < 0.0f) {
    if (!navSatTurnLive) {
      navSatTurnLive    = true;
      navSatTurnStartMs = millis();
    } else if ((uint32_t)(millis() - navSatTurnStartMs) >= NAV_STUCK_TURN_MS) {
      navSatTurnLive = false;
#if ENABLE_PENETRATION_MODE
      if (esekf.p[2] > PENETRATION_MIN_AGL_M) {
        navWindState   = NAV_WIND_PENETRATION;
        navWindStateMs = millis();
        safeSerialPrintln(F("[NAV] Wind beats glide speed - engaging penetration sweep."));
        // keep steering this frame; morph target changes in MODE_GLIDE
      } else {
        navWindState   = NAV_WIND_LEVEL_HOLD;
        navWindStateMs = millis();
        safeSerialPrintln(F("[NAV] Wind too strong, too low for penetration - level hold."));
        return ROLL_TARGET_DEG;
      }
#else
      navWindState   = NAV_WIND_LEVEL_HOLD;
      navWindStateMs = millis();
      safeSerialPrintln(F("[NAV] Turn not closing (wind > airspeed?) - holding wings level."));
      return ROLL_TARGET_DEG;
#endif
    }
  } else {
    navSatTurnLive = false;
  }

  return cmd;
#else
  return ROLL_TARGET_DEG;
#endif
}

// Wrapper: stores the commanded roll in navRollCmdDeg for the CSV log.
static float navRollTargetDeg() {
  navRollCmdDeg = navRollTargetCompute();
  return navRollCmdDeg;
}

// ========================= Cascade PID (M3) =========================
//
// Outer loop: angle error (deg) → desired angular rate (deg/s).
//   pidRateTargetRoll/Pitch = -Kp_outer · angleError
//
// Inner loop: rate error (deg/s) → servo deflection (deg).
//   u = Kp_inner · rateError + Ki_inner · integrator
//
// Mixing (wing servos act as elevons):
//   left  = pitch + roll   (symmetric pitch, differential roll)
//   right = pitch - roll
//
// rollTargetDeg comes from navRollTargetDeg() (GPS guidance) or is
// ROLL_TARGET_DEG (wings level) when navigation is unavailable.

static void clearPidState() {
  pidRateIntRoll     = 0.0f;
  pidRateIntPitch    = 0.0f;
  pidRateTargetRoll  = 0.0f;
  pidRateTargetPitch = 0.0f;
  uRollDeg  = 0.0f;
  uPitchDeg = 0.0f;
}

static void updateCascadePid(float dt, float rollTargetDeg) {
  // Outer loop
  const float rollErr  = deadband(rollRad *RAD_TO_DEG_F - rollTargetDeg,    ANGLE_DEADBAND_DEG);
  const float pitchErr = deadband(pitchRad*RAD_TO_DEG_F - PITCH_TARGET_DEG, ANGLE_DEADBAND_DEG);
  pidRateTargetRoll  = clampfLocal(-KP_OUTER_ROLL  * rollErr,
                                   -RATE_TARGET_LIMIT_DPS, RATE_TARGET_LIMIT_DPS);
  pidRateTargetPitch = clampfLocal(-KP_OUTER_PITCH * pitchErr,
                                   -RATE_TARGET_LIMIT_DPS, RATE_TARGET_LIMIT_DPS);

  // Inner loop — subtract the ESEKF-estimated gyro bias before use.
  // Raw imu.gyro still contains bias; esekf.bg tracks it online.
  const float measRollDps  = deadband((imu.gyro[0] - esekf.bg[0])*RAD_TO_DEG_F, RATE_DEADBAND_DPS);
  const float measPitchDps = deadband((imu.gyro[1] - esekf.bg[1])*RAD_TO_DEG_F, RATE_DEADBAND_DPS);
  const float eRoll  = pidRateTargetRoll  - measRollDps;
  const float ePitch = pidRateTargetPitch - measPitchDps;

  pidRateIntRoll  = clampfLocal(pidRateIntRoll  + eRoll *dt,
                                -INTEGRATOR_LIMIT_DEG, INTEGRATOR_LIMIT_DEG);
  pidRateIntPitch = clampfLocal(pidRateIntPitch + ePitch*dt,
                                -INTEGRATOR_LIMIT_DEG, INTEGRATOR_LIMIT_DEG);

  uRollDeg  = clampfLocal(KP_INNER_ROLL *eRoll  + KI_INNER_ROLL *pidRateIntRoll,
                           -CMD_LIMIT_DEG, CMD_LIMIT_DEG);
  uPitchDeg = clampfLocal(KP_INNER_PITCH*ePitch + KI_INNER_PITCH*pidRateIntPitch,
                           -CMD_LIMIT_DEG, CMD_LIMIT_DEG);

  // Elevon mixing: both servos are centred at PID_NEUTRAL_DEG (90°).
  // WING_FLAT_* positions are used only for fold/deploy geometry, not here.
  leftServoDeg  = clampfLocal(PID_NEUTRAL_DEG + uPitchDeg + uRollDeg,
                               SERVO_MIN_DEG, SERVO_MAX_DEG);
  rightServoDeg = clampfLocal(PID_NEUTRAL_DEG + uPitchDeg - uRollDeg,
                               SERVO_MIN_DEG, SERVO_MAX_DEG);
}

// ========================= Mission state machine =========================

static void setFlightMode(FlightMode next) {
  if (next == flightMode) return;
  flightMode   = next;
  modeStartUs  = micros();
  modeElapsedS = 0.0f;

  if (next == MODE_DEPLOYING) {
    // Remember morph position at transition time so ramp starts from the right angle.
    morphDeployStart = morphServoDeg;
  }
  if (next == MODE_GLIDE) {
    clearPidState();
  }
  if (next == MODE_APPROACH) {
    // Close to target now — penetration/hold no longer applies; make sure
    // the wings reopen fully for the approach and heli transition.
    navWindState = NAV_WIND_NORMAL;
  }
  if (next == MODE_HELI_DESCENT) {
    // Seed the descent-rate filter with the CURRENT descent rate, not zero.
    // Seeding with 0 made morphAdj start at -20° (clamped to MORPH_MIN) and
    // the servo step 180° → 70° at entry; seeding with the real value makes
    // the morph transition continuous.
    heliVdFilt = -esekf.v[2];
  }

  serialMutex.lock();
  Serial.print(F("[M] -> "));
  Serial.println(modeName(next));
  serialMutex.unlock();
}

static void updateMission(float dt) {
  modeElapsedS = (micros() - modeStartUs) * 1.0e-6f;

  const float speed = sqrtf(esekf.v[0]*esekf.v[0] +
                            esekf.v[1]*esekf.v[1] +
                            esekf.v[2]*esekf.v[2]);
  // AGL altitude (NEU: up = positive), relative to GPS origin.
  const float agl   = esekf.p[2];
  // Downward velocity (positive = falling).
  const float vDown = -esekf.v[2];

  switch (flightMode) {

    // ----------------------------------------------------------------
    case MODE_CARRIED: {
      // M0: Folded, carried by drone. Hold fold position.
      // Free-fall detector watches for |accel| < 0.3 g for 125 ms.
      leftServoDeg  = WING_FOLD_LEFT_DEG;
      rightServoDeg = WING_FOLD_RIGHT_DEG;
      morphServoDeg = MORPH_FOLD_DEG;
      tailServoDeg  = TAIL_HOLD_DEG;

      // Free-fall detection: in free fall gravity is cancelled;
      // accelerometer reads ≈0 m/s². See FREE_FALL_THRESHOLD/CONFIRM notes.
      const float aN = sqrtf(imu.accel[0]*imu.accel[0] +
                             imu.accel[1]*imu.accel[1] +
                             imu.accel[2]*imu.accel[2]);
      if (aN < FREE_FALL_THRESHOLD_MPS2) {
        if (freeFallCount < FREE_FALL_CONFIRM_FRAMES) freeFallCount++;
      } else {
        freeFallCount = 0;
      }
      if (freeFallCount >= FREE_FALL_CONFIRM_FRAMES) {
        freeFallCount = 0;
        setFlightMode(MODE_FREE_FALL);
      }
      break;
    }

    // ----------------------------------------------------------------
    case MODE_FREE_FALL: {
      // M1: Released, building speed, still folded (no drag = faster spin-up).
      // Deployment is triggered by speed (primary) or altitude floor (failsafe).
      // Both require v[2] < 0 (descending) to prevent accidental trigger
      // while ascending through the same altitude on the way up.
      leftServoDeg  = WING_FOLD_LEFT_DEG;
      rightServoDeg = WING_FOLD_RIGHT_DEG;
      morphServoDeg = MORPH_FOLD_DEG;
      tailServoDeg  = TAIL_HOLD_DEG;

      const bool descending = (esekf.v[2] < -0.5f);

      // Primary: enough speed AND safe altitude remaining for deployment.
      const bool normalOpen = descending &&
                              (speed >= V_OPEN_MIN_MPS) &&
                              (agl   >= H_OPEN_MIN_M);
      // Failsafe: too close to ground — open regardless of speed.
      // See H_FORCE_OPEN_M annotation in constants.
      const bool forceOpen  = descending && (agl <= H_FORCE_OPEN_M);

      if (normalOpen || forceOpen) {
        if (forceOpen && !normalOpen) {
          safeSerialPrintln(F("[M1] FORCE OPEN: altitude floor reached."));
        }
        setFlightMode(MODE_DEPLOYING);
      }
      break;
    }

    // ----------------------------------------------------------------
    case MODE_DEPLOYING: {
      // M2: Morph sweeps from fold angle to fully open in T2_OPEN_S seconds.
      // Left/right wings stay at fold AoA until morph clears to prevent
      // mechanical contact (±30° bias from flat).
      leftServoDeg  = WING_FOLD_LEFT_DEG;
      rightServoDeg = WING_FOLD_RIGHT_DEG;
      tailServoDeg  = TAIL_HOLD_DEG;

      const float progress  = clampfLocal(modeElapsedS / T2_OPEN_S, 0.f, 1.f);
      morphServoDeg = morphDeployStart + progress*(MORPH_OPEN_DEG - morphDeployStart);

      if (modeElapsedS >= T2_OPEN_S) {
        morphServoDeg = MORPH_OPEN_DEG;
        // Hand over at PID_NEUTRAL_DEG so M3's first PID frame (which centres
        // on the same neutral) causes no servo step.
        leftServoDeg  = PID_NEUTRAL_DEG;
        rightServoDeg = PID_NEUTRAL_DEG;
        setFlightMode(MODE_GLIDE);
      }
      break;
    }

    // ----------------------------------------------------------------
    case MODE_GLIDE: {
      // M3: Wings open. Cascade PID holds attitude; roll target comes from
      // GPS bank-to-turn guidance. Morph follows the wind state machine:
      // partial sweep while penetrating a headwind, fully open otherwise.
      // (navRollTargetDeg() updates navWindState, so morph is set after.)
      tailServoDeg  = TAIL_HOLD_DEG;
      updateCascadePid(dt, navRollTargetDeg());
      morphServoDeg = (navWindState == NAV_WIND_PENETRATION)
                        ? PENETRATION_MORPH_DEG
                        : MORPH_OPEN_DEG;

#if ENABLE_APPROACH_PHASES
      if (!gpsOriginSet) break;

      // Altitude floor: below H_FORCE_APPROACH_M there is not enough height
      // to keep gliding toward the target — force the heli transition NOW,
      // regardless of distance. Mirrors H_FORCE_OPEN_M in M1, including the
      // descending gate so ESEKF glitches upward cannot trigger it.
      const bool descendingM3 = (esekf.v[2] < -0.5f);
      if (descendingM3 && agl <= H_FORCE_APPROACH_M) {
        safeSerialPrintln(F("[M3] FORCE APPROACH: altitude floor reached."));
        approachCount = 0;
        setFlightMode(MODE_APPROACH);
        break;
      }

      const float dn = esekf.p[0] - APPROACH_TARGET_N_M;
      const float de = esekf.p[1] - APPROACH_TARGET_E_M;
      if (sqrtf(dn*dn + de*de) <= APPROACH_RADIUS_M) {
        if (approachCount < APPROACH_CONFIRM_CYCLES) approachCount++;
      } else {
        approachCount = 0;
      }
      if (approachCount >= APPROACH_CONFIRM_CYCLES) {
        approachCount = 0;
        setFlightMode(MODE_APPROACH);
      }
#endif
      break;
    }

    // ----------------------------------------------------------------
    case MODE_APPROACH: {
      // M4: Inside approach zone. PID continues; hold 0.5 s then
      // transition to helicopter configuration.
      morphServoDeg = MORPH_OPEN_DEG;
      tailServoDeg  = TAIL_HOLD_DEG;
      updateCascadePid(dt, navRollTargetDeg());

      if (modeElapsedS >= 0.5f) {
        setFlightMode(MODE_HELI_DESCENT);
      }
      break;
    }

    // ----------------------------------------------------------------
    case MODE_HELI_DESCENT: {
      // M5: Wings in autorotation configuration.
      // Morph angle modulates descent rate:
      //   faster descent → increase morph (more blade area → more drag/lift).
      //   slower descent → decrease morph.
      // heliVdFilt is a low-pass of measured downward velocity to filter GPS noise.
      leftServoDeg  = HELI_LEFT_DEG;
      rightServoDeg = HELI_RIGHT_DEG;
      tailServoDeg  = TAIL_HOLD_DEG;

      heliVdFilt += HELI_VD_FILTER_ALPHA * (vDown - heliVdFilt);

      // Dead zone: [NORMAL, FAST] = [2.5, 3.5] m/s → no adjustment.
      // Outside that band, adjustment is proportional to deviation from the
      // respective boundary — continuous at both edges (morphAdj = 0 at each).
      float morphAdj = 0.0f;
      if (heliVdFilt > HELI_FAST_DESCENT_MPS) {
        // Descending too fast: open morph further to add rotor area, slow down.
        morphAdj = HELI_GAIN_DEG_PER_MPS * (heliVdFilt - HELI_FAST_DESCENT_MPS);
      } else if (heliVdFilt < HELI_NORMAL_DESCENT_MPS) {
        // Descending too slowly: close morph to reduce area, speed up.
        morphAdj = HELI_GAIN_DEG_PER_MPS * (heliVdFilt - HELI_NORMAL_DESCENT_MPS);
      }
      morphServoDeg = clampfLocal(
          HELI_MORPH_BASE_DEG + morphAdj,
          HELI_MORPH_MIN_DEG,
          HELI_MORPH_MAX_DEG);
      break;
    }

    default: break;
  }

  writeAllServos();
}
